package net.dodiya.signalman.data

import com.google.gson.Gson
import com.google.gson.GsonBuilder
import com.google.gson.annotations.SerializedName

data class ExportData(
    @SerializedName("version")
    val version: Int = 1,
    @SerializedName("exported_at")
    val exportedAt: Long = System.currentTimeMillis(),
    @SerializedName("app_name")
    val appName: String = "Signalman",
    @SerializedName("rules")
    val rules: List<ExportedRule>,
)

data class ExportedRule(
    @SerializedName("name")
    val name: String,
    @SerializedName("filters")
    val filters: List<Filter>,
    @SerializedName("logical_operator")
    val logicalOperator: LogicalOperator,
    @SerializedName("target_package")
    val targetPackage: String?,
    @SerializedName("is_transform_enabled")
    val isTransformEnabled: Boolean,
    @SerializedName("replace_pattern")
    val replacePattern: String?,
    @SerializedName("replacement")
    val replacement: String?,
    @SerializedName("url_component_replacements")
    val urlComponentReplacements: List<UrlComponentReplacement>,
    @SerializedName("transform_mode")
    val transformMode: TransformMode,
    @SerializedName("description")
    val description: String,
    @SerializedName("is_enabled")
    val isEnabled: Boolean,
    @SerializedName("priority")
    val priority: Int,
    @SerializedName("example_url")
    val exampleUrl: String?,
) {
    fun toRule(): Rule =
        Rule(
            id = 0,
            name = name,
            filters = filters,
            logicalOperator = logicalOperator,
            targetPackage = targetPackage,
            isTransformEnabled = isTransformEnabled,
            replacePattern = replacePattern,
            replacement = replacement,
            urlComponentReplacements = urlComponentReplacements,
            transformMode = transformMode,
            description = description,
            isEnabled = isEnabled,
            priority = priority,
            isAutoGenerated = false,
            exampleUrl = exampleUrl,
        )

    companion object {
        fun fromRule(rule: Rule): ExportedRule =
            ExportedRule(
                name = rule.name,
                filters = rule.filters,
                logicalOperator = rule.logicalOperator,
                targetPackage = rule.targetPackage,
                isTransformEnabled = rule.isTransformEnabled,
                replacePattern = rule.replacePattern,
                replacement = rule.replacement,
                urlComponentReplacements = rule.urlComponentReplacements,
                transformMode = rule.transformMode,
                description = rule.description,
                isEnabled = rule.isEnabled,
                priority = rule.priority,
                exampleUrl = rule.exampleUrl,
            )
    }
}

object RuleExporter {
    private val gson: Gson = GsonBuilder().setPrettyPrinting().create()

    fun exportRules(rules: List<Rule>): String {
        val exportedRules = rules.map { ExportedRule.fromRule(it) }
        val exportData = ExportData(rules = exportedRules)
        return gson.toJson(exportData)
    }

    fun importRules(json: String): List<Rule>? =
        try {
            val exportData = gson.fromJson(json, ExportData::class.java)
            exportData.rules.map { it.toRule() }
        } catch (e: Exception) {
            null
        }
}
