package net.dodiya.signalman.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverter
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken

enum class MatchType {
    CONTAINS {
        override val userFriendlyName = "Contains"
    },
    EQUALS {
        override val userFriendlyName = "Equals"
    },
    STARTS_WITH {
        override val userFriendlyName = "Starts with"
    },
    ENDS_WITH {
        override val userFriendlyName = "Ends with"
    },
    REGEX {
        override val userFriendlyName = "Regex"
    }, ;

    abstract val userFriendlyName: String
}

enum class LogicalOperator {
    AND,
    OR,
}

enum class TransformMode {
    SIMPLE,
    ADVANCED,
}

data class Filter(
    val pattern: String,
    val matchType: MatchType = MatchType.REGEX,
)

@Entity(tableName = "rules")
data class Rule(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val filters: List<Filter> = emptyList(),
    val logicalOperator: LogicalOperator = LogicalOperator.AND,
    val targetPackage: String?,
    val isTransformEnabled: Boolean = false,
    val replacePattern: String? = null,
    val replacement: String? = null,
    val urlComponentReplacements: List<UrlComponentReplacement> = emptyList(),
    val transformMode: TransformMode = TransformMode.SIMPLE,
    val description: String = "",
    val isEnabled: Boolean = true,
    val priority: Int = 0,
    val isAutoGenerated: Boolean = false,
    val exampleUrl: String? = null,
) {
    val pattern: String get() = filters.firstOrNull()?.pattern ?: ""
    val matchType: MatchType get() = filters.firstOrNull()?.matchType ?: MatchType.REGEX
}

class Converters {
    private val gson = Gson()

    @TypeConverter
    fun fromFilterList(value: List<Filter>): String = gson.toJson(value)

    @TypeConverter
    fun toFilterList(value: String): List<Filter> {
        val listType = object : TypeToken<List<Filter>>() {}.type
        return gson.fromJson(value, listType)
    }

    @TypeConverter
    fun fromUrlComponentReplacementList(value: List<UrlComponentReplacement>): String = gson.toJson(value)

    @TypeConverter
    fun toUrlComponentReplacementList(value: String): List<UrlComponentReplacement> {
        if (value.isEmpty()) return emptyList()
        val listType = object : TypeToken<List<UrlComponentReplacement>>() {}.type
        return gson.fromJson(value, listType)
    }
}
