package net.dodiya.signalman.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

@Serializable
data class ExportData(
    @SerialName("version")
    val version: Int = 1,
    @SerialName("exported_at")
    val exportedAt: Long = System.currentTimeMillis(),
    @SerialName("app_name")
    val appName: String = "Signalman",
    @SerialName("rules")
    val rules: List<ExportedRule>,
)

@Serializable
data class ExportedRule(
    @SerialName("name")
    val name: String,
    @SerialName("filters")
    val filters: List<Filter>,
    @SerialName("logical_operator")
    val logicalOperator: LogicalOperator,
    @SerialName("target_package")
    val targetPackage: String,
    @SerialName("transform_mode")
    val transformMode: TransformMode,
    @SerialName("description")
    val description: String,
    @SerialName("is_enabled")
    val isEnabled: Boolean,
    @SerialName("is_clean_url")
    val isCleanUrl: Boolean = false,
    @SerialName("priority")
    val priority: Int,
    @SerialName("example_url")
    val exampleUrl: String?,
) {
    fun toRule(): Rule =
        Rule(
            id = 0,
            name = name,
            filters = filters,
            logicalOperator = logicalOperator,
            targetPackage = targetPackage,
            transformMode = transformMode,
            description = description,
            isEnabled = isEnabled,
            isCleanUrl = isCleanUrl,
            priority = priority,
            isAutoGenerated = false,
            exampleUrl = exampleUrl,
        )

    companion object {
        fun fromRule(rule: Rule): ExportedRule =
            ExportedRule(
                name = rule.name,
                filters = rule.filters,
                logicalOperator = rule.logicalOperator,
                targetPackage = rule.targetPackage,
                transformMode = rule.transformMode,
                description = rule.description,
                isEnabled = rule.isEnabled,
                isCleanUrl = rule.isCleanUrl,
                priority = rule.priority,
                exampleUrl = rule.exampleUrl,
            )
    }
}

object RuleExporter {
    private val json = Json { prettyPrint = true }

    fun exportRules(rules: List<Rule>): String {
        val exportedRules = rules.map { ExportedRule.fromRule(it) }
        val exportData = ExportData(rules = exportedRules)
        return json.encodeToString(exportData)
    }

    fun importRules(jsonString: String): List<Rule>? =
        try {
            val exportData: ExportData = json.decodeFromString(jsonString)
            exportData.rules.map { it.toRule() }
        } catch (e: kotlinx.serialization.SerializationException) {
            android.util.Log.e("RuleExporter", "Failed to parse JSON", e)
            null
        } catch (e: IllegalArgumentException) {
            android.util.Log.e("RuleExporter", "Invalid JSON format", e)
            null
        }
}
