package net.dodiya.signalman.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverter
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

@Serializable
enum class MatchType {
    CONTAINS,
    EQUALS,
    STARTS_WITH,
    ENDS_WITH,
    REGEX,
    ;

    val userFriendlyName: String
        get() =
            when (this) {
                CONTAINS -> "Contains"
                EQUALS -> "Equals"
                STARTS_WITH -> "Starts with"
                ENDS_WITH -> "Ends with"
                REGEX -> "Regex"
            }
}

@Serializable
enum class LogicalOperator {
    AND,
    OR,
}

@Serializable
sealed class TransformMode {
    @Serializable
    data class Simple(
        val replacePattern: String = "",
        val replacement: String = "",
    ) : TransformMode()

    @Serializable
    data class Advanced(
        val urlComponentReplacements: List<UrlComponentReplacement> = emptyList(),
    ) : TransformMode()
}

@Serializable
data class Filter(
    val pattern: String,
    val matchType: MatchType = MatchType.REGEX,
)

@Entity(tableName = "rules")
@Serializable
data class Rule(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val filters: List<Filter> = emptyList(),
    val logicalOperator: LogicalOperator = LogicalOperator.AND,
    val targetPackage: String,
    val transformMode: TransformMode = TransformMode.Simple(),
    val description: String = "",
    val isEnabled: Boolean = true,
    @ColumnInfo(defaultValue = "0")
    val isCleanUrl: Boolean = false,
    val priority: Int = 0,
    val isAutoGenerated: Boolean = false,
    val exampleUrl: String? = null,
)

@Serializable
data class UrlComponentReplacement(
    val component: UrlComponent,
    val replacement: String,
    val isEnabled: Boolean = true,
)

@Serializable
enum class UrlComponent(
    val displayName: String,
    val description: String,
) {
    SCHEME("Scheme", "e.g., https, http, ftp"),
    HOST("Host", "e.g., google, youtube"),
    DOMAIN("Domain", "e.g., com, net, org"),
    PORT("Port", "e.g., 8080, 443"),
    PATH("Path", "e.g., /watch, /videos/123"),
    QUERY("Query", "e.g., v=abc123&t=60"),
    FRAGMENT("Fragment", "e.g., section1, timestamp"),
    USER_INFO("User Info", "e.g., user:password"),
}

class Converters {
    private val json = Json { ignoreUnknownKeys = true }

    @TypeConverter
    fun fromFilterList(value: List<Filter>): String = json.encodeToString(value)

    @TypeConverter
    fun toFilterList(value: String): List<Filter> = json.decodeFromString(value)

    @TypeConverter
    fun fromUrlComponentReplacementList(value: List<UrlComponentReplacement>): String = json.encodeToString(value)

    @TypeConverter
    fun toUrlComponentReplacementList(value: String): List<UrlComponentReplacement> {
        if (value.isEmpty()) return emptyList()
        return json.decodeFromString(value)
    }

    @TypeConverter
    fun fromTransformMode(value: TransformMode): String = json.encodeToString(value)

    @TypeConverter
    fun toTransformMode(value: String): TransformMode = json.decodeFromString(value)
}
