package net.dodiya.signalman.domain

import android.net.Uri
import net.dodiya.signalman.data.Filter
import net.dodiya.signalman.data.MatchType
import net.dodiya.signalman.data.Rule
import net.dodiya.signalman.data.RuleRepository

class CreateAutoRuleUseCase(
    private val repository: RuleRepository,
) {
    suspend operator fun invoke(
        uri: Uri,
        pkgName: String,
        mode: Int,
    ) {
        val domain = uri.host ?: ""
        val url = uri.toString()
        val rule =
            when (mode) {
                1 ->
                    Rule(
                        name = "Auto: $url",
                        filters = listOf(Filter(pattern = url, matchType = MatchType.EQUALS)),
                        targetPackage = pkgName,
                        isAutoGenerated = true,
                    )
                2 ->
                    if (domain.isNotEmpty()) {
                        Rule(
                            name = "Auto: $domain",
                            filters = listOf(Filter(pattern = domain, matchType = MatchType.CONTAINS)),
                            targetPackage = pkgName,
                            isAutoGenerated = true,
                        )
                    } else {
                        null
                    }
                else -> null
            }

        rule?.let { repository.insert(it) }
    }
}
