package net.dodiya.signalman.ui

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.List
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Clear
import androidx.compose.material.icons.filled.Delete
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.Search
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.ListItem
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.NavigationBar
import androidx.compose.material3.NavigationBarItem
import androidx.compose.material3.OutlinedCard
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.RadioButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import net.dodiya.signalman.data.AppInfo
import net.dodiya.signalman.data.Rule

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun RuleListScreen(
    viewModel: RuleViewModel,
    onAddRule: (String, String) -> Unit,
    onEditRule: (Int) -> Unit,
    onNavigateToSettings: () -> Unit = {},
) {
    val rules by viewModel.allRules.collectAsStateWithLifecycle()
    val installedApps by viewModel.installedApps.collectAsStateWithLifecycle()
    val globalDefault by viewModel.globalDefaultPackage.collectAsStateWithLifecycle()
    val isAutoEnabled by viewModel.isAutoRuleGenerationEnabled.collectAsStateWithLifecycle()

    var selectedTab by remember { mutableIntStateOf(0) }
    var showAddRuleDialog by remember { mutableStateOf(false) }

    val filteredRules =
        remember(rules, selectedTab) {
            when (selectedTab) {
                0 -> rules.filter { !it.isAutoGenerated }
                1 -> rules.filter { it.isAutoGenerated }
                else -> emptyList()
            }
        }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Signalman") },
            )
        },
        bottomBar = {
            NavigationBar {
                NavigationBarItem(
                    selected = selectedTab == 0,
                    onClick = { selectedTab = 0 },
                    icon = { Icon(Icons.AutoMirrored.Filled.List, contentDescription = null) },
                    label = { Text("Custom") },
                )
                NavigationBarItem(
                    selected = selectedTab == 1,
                    onClick = { selectedTab = 1 },
                    icon = { Icon(Icons.Default.AutoAwesome, contentDescription = null) },
                    label = { Text("Auto") },
                )
                NavigationBarItem(
                    selected = false,
                    onClick = onNavigateToSettings,
                    icon = { Icon(Icons.Default.Settings, contentDescription = null) },
                    label = { Text("Settings") },
                )
            }
        },
        floatingActionButton = {
            if (selectedTab == 0) {
                FloatingActionButton(
                    onClick = { showAddRuleDialog = true },
                    modifier = Modifier.padding(bottom = 16.dp),
                ) {
                    Icon(Icons.Default.Add, contentDescription = "Add Rule")
                }
            }
        },
    ) { padding ->
        Column(modifier = Modifier.padding(padding)) {
            if (selectedTab == 1) {
                AutoRulesHeader(
                    isAutoEnabled = isAutoEnabled,
                    onAutoEnabledChange = { viewModel.setAutoRuleGenerationEnabled(it) },
                    globalDefault = globalDefault,
                    installedApps = installedApps,
                    onSelectDefault = { viewModel.setGlobalDefault(it) },
                )
                HorizontalDivider()
            }

            if (filteredRules.isEmpty()) {
                Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                    Text(if (selectedTab == 0) "No custom rules yet." else "No auto-generated rules yet.")
                }
            } else {
                LazyColumn(modifier = Modifier.fillMaxSize()) {
                    items(filteredRules) { rule ->
                        RuleItem(
                            rule = rule,
                            onDelete = { viewModel.delete(rule) },
                            onEdit = { onEditRule(rule.id) },
                        )
                    }
                }
            }
        }

        if (showAddRuleDialog) {
            AddRuleDialog(
                onDismiss = { showAddRuleDialog = false },
                onConfirm = { name, url ->
                    showAddRuleDialog = false
                    onAddRule(name, url)
                },
            )
        }
    }
}

@Composable
fun AutoRulesHeader(
    isAutoEnabled: Boolean,
    onAutoEnabledChange: (Boolean) -> Unit,
    globalDefault: String?,
    installedApps: List<AppInfo>,
    onSelectDefault: (String?) -> Unit,
) {
    var showAppPicker by remember { mutableStateOf(false) }

    Column(modifier = Modifier.padding(16.dp)) {
        Row(verticalAlignment = Alignment.CenterVertically) {
            Column(modifier = Modifier.weight(1f)) {
                Text("Enable auto rule generation", style = MaterialTheme.typography.titleMedium)
                Text(
                    "Prompt to create rules for new links",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.outline,
                )
            }
            Switch(checked = isAutoEnabled, onCheckedChange = onAutoEnabledChange)
        }

        if (!isAutoEnabled) {
            Spacer(modifier = Modifier.height(16.dp))
            Text("Fallback Action", style = MaterialTheme.typography.labelLarge)

            val selectedAppName = installedApps.find { it.packageName == globalDefault }?.name ?: "System Chooser"

            OutlinedCard(
                modifier =
                    Modifier
                        .fillMaxWidth()
                        .padding(vertical = 8.dp)
                        .clickable { showAppPicker = true },
            ) {
                Row(
                    modifier = Modifier.padding(16.dp),
                    verticalAlignment = Alignment.CenterVertically,
                ) {
                    Column(modifier = Modifier.weight(1f)) {
                        Text("Default App", style = MaterialTheme.typography.labelSmall)
                        Text(selectedAppName, style = MaterialTheme.typography.bodyLarge)
                    }
                    if (globalDefault != null) {
                        IconButton(onClick = { onSelectDefault(null) }) {
                            Icon(Icons.Default.Clear, contentDescription = "Clear Default")
                        }
                    }
                }
            }
        }
    }

    if (showAppPicker) {
        AppPickerDialog(
            currentDefault = globalDefault,
            installedApps = installedApps,
            onDismiss = { showAppPicker = false },
            onSelect = {
                onSelectDefault(it)
                showAppPicker = false
            },
        )
    }
}

@Composable
fun AppPickerDialog(
    currentDefault: String?,
    installedApps: List<AppInfo>,
    onDismiss: () -> Unit,
    onSelect: (String?) -> Unit,
) {
    var searchQuery by remember { mutableStateOf("") }
    val filteredApps =
        remember(searchQuery, installedApps) {
            installedApps.filter {
                it.name.contains(searchQuery, ignoreCase = true) ||
                    it.packageName.contains(searchQuery, ignoreCase = true)
            }
        }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Select Default App") },
        text = {
            Column(modifier = Modifier.heightIn(max = 400.dp)) {
                OutlinedTextField(
                    value = searchQuery,
                    onValueChange = { searchQuery = it },
                    label = { Text("Search Apps") },
                    modifier = Modifier.fillMaxWidth(),
                    leadingIcon = { Icon(Icons.Default.Search, null) },
                    trailingIcon = {
                        if (searchQuery.isNotEmpty()) {
                            IconButton(
                                onClick = { searchQuery = "" },
                            ) { Icon(Icons.Default.Clear, null) }
                        }
                    },
                )

                Spacer(modifier = Modifier.height(8.dp))

                LazyColumn(modifier = Modifier.weight(1f)) {
                    item {
                        ListItem(
                            headlineContent = { Text("System Chooser (None)") },
                            modifier = Modifier.clickable { onSelect(null) },
                            trailingContent = { if (currentDefault == null) RadioButton(selected = true, onClick = null) },
                        )
                    }
                    items(filteredApps) { app ->
                        ListItem(
                            headlineContent = { Text(app.name) },
                            supportingContent = { Text(app.packageName) },
                            modifier = Modifier.clickable { onSelect(app.packageName) },
                            trailingContent = { if (currentDefault == app.packageName) RadioButton(selected = true, onClick = null) },
                        )
                    }
                }
            }
        },
        confirmButton = {
            TextButton(onClick = onDismiss) { Text("Cancel") }
        },
    )
}

@Composable
fun AddRuleDialog(
    onDismiss: () -> Unit,
    onConfirm: (String, String) -> Unit,
) {
    var ruleName by remember { mutableStateOf("") }
    var exampleUrl by remember { mutableStateOf("") }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("New Rule") },
        text = {
            Column {
                Text("Enter rule details", style = MaterialTheme.typography.bodyMedium)
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(
                    value = ruleName,
                    onValueChange = { ruleName = it },
                    label = { Text("Rule Name") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth().testTag("rule_name_input"),
                )
                Spacer(modifier = Modifier.height(8.dp))
                OutlinedTextField(
                    value = exampleUrl,
                    onValueChange = { exampleUrl = it },
                    label = { Text("Example URL (Optional)") },
                    placeholder = { Text("https://x.com/post/123") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth().testTag("example_url_input"),
                )
                Text(
                    "Provide a sample link to test your rules live.",
                    style = MaterialTheme.typography.labelSmall,
                    color = MaterialTheme.colorScheme.outline,
                    modifier = Modifier.padding(top = 4.dp),
                )
            }
        },
        confirmButton = {
            Button(
                onClick = { if (ruleName.isNotBlank()) onConfirm(ruleName, exampleUrl) },
                enabled = ruleName.isNotBlank(),
            ) {
                Text("Next")
            }
        },
        dismissButton = {
            TextButton(onClick = onDismiss) {
                Text("Cancel")
            }
        },
    )
}

@Composable
fun RuleItem(
    rule: Rule,
    onDelete: () -> Unit,
    onEdit: () -> Unit,
) {
    Card(
        modifier =
            Modifier
                .fillMaxWidth()
                .padding(horizontal = 8.dp, vertical = 4.dp)
                .clickable { onEdit() },
    ) {
        Row(
            modifier =
                Modifier
                    .padding(16.dp)
                    .fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(text = rule.name, style = MaterialTheme.typography.titleMedium, maxLines = 1)
                Text(
                    text = rule.pattern,
                    style = MaterialTheme.typography.bodySmall,
                    maxLines = 1,
                    color = MaterialTheme.colorScheme.outline,
                )
                Text(text = "→ ${rule.targetPackage ?: "Chooser"}", style = MaterialTheme.typography.labelSmall)
            }
            Row {
                IconButton(onClick = onEdit) {
                    Icon(Icons.Default.Edit, contentDescription = "Edit")
                }
                IconButton(onClick = onDelete) {
                    Icon(Icons.Default.Delete, contentDescription = "Delete")
                }
            }
        }
    }
}
