package net.dodiya.signalman.ui.rulelist

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.List
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FloatingActionButton
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.NavigationBar
import androidx.compose.material3.NavigationBarItem
import androidx.compose.material3.Scaffold
import androidx.compose.material3.SnackbarHost
import androidx.compose.material3.SnackbarHostState
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import net.dodiya.signalman.R
import net.dodiya.signalman.ui.ImportExportState
import net.dodiya.signalman.ui.RuleViewModel
import net.dodiya.signalman.ui.SettingsContent
import net.dodiya.signalman.ui.SettingsViewModel

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun RuleListScreen(
    viewModel: RuleViewModel,
    settingsViewModel: SettingsViewModel,
    onAddRule: (String, String) -> Unit,
    onEditRule: (Int) -> Unit,
    onNavigateToImportExport: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val rules by viewModel.allRules.collectAsStateWithLifecycle()
    val installedApps by viewModel.installedApps.collectAsStateWithLifecycle()
    val globalDefault by viewModel.globalDefaultPackage.collectAsStateWithLifecycle()
    val isAutoEnabled by viewModel.isAutoRuleGenerationEnabled.collectAsStateWithLifecycle()

    var selectedTab by remember { mutableIntStateOf(0) }
    var showAddRuleDialog by remember { mutableStateOf(false) }

    val filteredRules =
        remember(rules, selectedTab) {
            when (selectedTab) {
                0 -> rules.filter { !it.isAutoGenerated }
                1 -> rules.filter { it.isAutoGenerated }
                else -> emptyList()
            }
        }

    val context = LocalContext.current
    val snackbarHostState = remember { SnackbarHostState() }
    val importExportState by settingsViewModel.importExportState.collectAsStateWithLifecycle()

    LaunchedEffect(importExportState) {
        when (val state = importExportState) {
            is ImportExportState.Success -> {
                snackbarHostState.showSnackbar(state.message)
                settingsViewModel.resetImportExportState()
            }
            is ImportExportState.Error -> {
                snackbarHostState.showSnackbar(state.message)
                settingsViewModel.resetImportExportState()
            }
            else -> {}
        }
    }

    Scaffold(
        modifier = modifier,
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        when (selectedTab) {
                            0 -> context.getString(R.string.nav_custom)
                            1 -> context.getString(R.string.nav_auto)
                            else -> context.getString(R.string.nav_settings)
                        },
                    )
                },
            )
        },
        snackbarHost = { SnackbarHost(snackbarHostState) },
        bottomBar = {
            NavigationBar {
                NavigationBarItem(
                    selected = selectedTab == 0,
                    onClick = { selectedTab = 0 },
                    icon = { Icon(Icons.AutoMirrored.Filled.List, contentDescription = null) },
                    label = { Text(context.getString(R.string.nav_custom)) },
                )
                NavigationBarItem(
                    selected = selectedTab == 1,
                    onClick = { selectedTab = 1 },
                    icon = { Icon(Icons.Default.AutoAwesome, contentDescription = null) },
                    label = { Text(context.getString(R.string.nav_auto)) },
                )
                NavigationBarItem(
                    selected = selectedTab == 2,
                    onClick = { selectedTab = 2 },
                    icon = { Icon(Icons.Default.Settings, contentDescription = null) },
                    label = { Text(context.getString(R.string.nav_settings)) },
                )
            }
        },
        floatingActionButton = {
            if (selectedTab == 0) {
                FloatingActionButton(
                    onClick = { showAddRuleDialog = true },
                    modifier = Modifier.padding(bottom = 16.dp).testTag("add_rule_fab"),
                ) {
                    Icon(Icons.Default.Add, contentDescription = context.getString(R.string.cd_add_rule))
                }
            }
        },
    ) { padding ->
        Column(modifier = Modifier.padding(padding)) {
            when (selectedTab) {
                0, 1 -> {
                    if (selectedTab == 1) {
                        AutoRulesHeader(
                            isAutoEnabled = isAutoEnabled,
                            onAutoEnabledChange = { viewModel.setAutoRuleGenerationEnabled(it) },
                            globalDefault = globalDefault,
                            installedApps = installedApps,
                            onSelectDefault = { viewModel.setGlobalDefault(it) },
                        )
                        HorizontalDivider()
                    }

                    if (filteredRules.isEmpty()) {
                        Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                            Text(
                                if (selectedTab == 0) {
                                    context.getString(R.string.no_custom_rules)
                                } else {
                                    context.getString(R.string.no_auto_rules)
                                },
                            )
                        }
                    } else {
                        LazyColumn(modifier = Modifier.fillMaxSize()) {
                            items(filteredRules) { rule ->
                                RuleItem(
                                    rule = rule,
                                    onDelete = { viewModel.delete(rule) },
                                    onEdit = { onEditRule(rule.id) },
                                )
                            }
                        }
                    }
                }
                2 -> {
                    SettingsContent(
                        onNavigateToImportExport = onNavigateToImportExport,
                        viewModel = settingsViewModel,
                    )
                }
            }
        }

        if (showAddRuleDialog) {
            AddRuleDialog(
                onDismiss = { showAddRuleDialog = false },
                onConfirm = { name, url ->
                    showAddRuleDialog = false
                    onAddRule(name, url)
                },
            )
        }
    }
}
